---
info:
  scm-url: "@scm.url@"
  build-url: "https://travis-ci.org/codecentric/spring-boot-admin"

logging:
  level:
    ROOT: info
    de.codecentric: trace
    org.springframework.web: debug
  file:
    name: "target/spring-boot-admin-3-graalvm.log"
  pattern:
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"

management:
  info:
    java:
      enabled: true
      env:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: spring-boot-admin-3-graalvm
  main:
    lazy-initialization: true
  boot:
    admin:
      client:
        url: http://localhost:8080
      ui:
        external-views:
          - label: 'Is it Christmas yet?'
            url: https://isitchristmas.com/
