---
logging:
  level:
    ROOT: info
    de.codecentric: trace
    org.springframework.web: debug
  file:
    name: "target/spring-boot-admin-3.log"
  pattern:
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    jolokia:
      enabled: true
    refresh:
      enabled: true
    restart:
      enabled: true
    shutdown:
      enabled: true
    env:
      post:
        enabled: true
    health:
      show-details: ALWAYS

spring:
  application:
    name: spring-boot-admin-3-graalvm
  jmx:
    enabled: true
  main:
    lazy-initialization: true

---
# tag::customization-external-views[]
spring:
  boot:
    admin:
      ui:
        external-views:
          - label: "ðŸš€"
            url: https://codecentric.de
            order: 2000
      # context-path: test/
      client:
        url: http://localhost:8080
        instance:
          service-base-url: http://localhost:8080
# end::customization-external-views[]
