---
info:
  scm-url: "@scm.url@"
  build-url: "https://travis-ci.org/codecentric/spring-boot-admin"

logging:
  file:
    name: "target/boot-admin-sample-servlet.log"
  pattern:
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

spring:
  application:
    name: spring-boot-admin-sample-servlet
  profiles:
    active:
      - secure
  boot:
    admin:
      client:
        url: http://localhost:8080
        instance:
          metadata:
            tags:
              environment: test
---

# tag::customization-external-views[]
spring:
  boot:
    admin:
      ui:
        external-views:
          - label: "ðŸš€"
            url: http://codecentric.de
            order: 2000
# end::customization-external-views[]

---
spring:
  profiles: dev
  boot:
    admin:
      ui:
        cache:
          no-cache: true
        template-location: file:@project.basedir@/../../spring-boot-admin-server-ui/target/dist/
        resource-locations: file:@project.basedir@/../../spring-boot-admin-server-ui/target/dist/
        cache-templates: false
        extension-resource-locations: file:@project.basedir@/../spring-boot-admin-sample-custom-ui/target/dist/

---
spring:
  profiles: insecure

info.tags.security: insecure

---
spring:
  profiles: secure
  security:
    user:
      name: "user"
      password: "password"
  boot:
    admin:
      client:
        username: "user"       #These two are needed so that the client
        password: "password"   #can register at the protected server api
        instance:
          metadata:
            user.name: "user"         #These two are needed so that the server
            user.password: "password" #can access the protected client endpoints

info.tags.security: secured

